<?php
namespace console\template\auth\b_1013_20181012_backend;

/**
 * @author: pengqiucheng<pengqiucheng@julive.com>
 * @date: 2018/8/29
 * [
'auth_name'=>'',	//权限名称
'auth_url'=>'',		//权限路由
'parent_url'=>'',	//父级权限路由
'role_type'=>'',    //角色类型 add新增角色 reduce减少角色 recover覆盖
'role'=>[],			//角色数组 all表示所有角色
'creator'=>'',		//创建人姓名
]
 */

use common\constants\CommonConstant;
use common\constants\RbacConstant;

return [
    [
        'auth_name' => '放量计划',
        'auth_url'  => 'cj-project-volume',
        'parent_url'=>  'yw-project-list',
        'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '新增放量计划',
        'auth_url'  => 'cj-project-volume/create',
        'parent_url'=>  'cj-project-volume',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  [
            RbacConstant::$role_db_manager,
            RbacConstant::$role_bd_specialist,
            RbacConstant::$role_business_charger,
            RbacConstant::$role_channel_charger,
            RbacConstant::$role_channel_manager,
            RbacConstant::$role_data_operation_specialist,
            RbacConstant::$role_estate_expand,
            RbacConstant::$role_field_manager,
            RbacConstant::$role_operation_manager,
            RbacConstant::$role_operation_interns,
            RbacConstant::$role_project_charger,
        ],
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '编辑放量计划',
        'auth_url'  => 'cj-project-volume/update',
        'parent_url'=>  'cj-project-volume',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  [
            RbacConstant::$role_db_manager,
            RbacConstant::$role_bd_specialist,
            RbacConstant::$role_business_charger,
            RbacConstant::$role_channel_charger,
            RbacConstant::$role_channel_manager,
            RbacConstant::$role_data_operation_specialist,
            RbacConstant::$role_estate_expand,
            RbacConstant::$role_field_manager,
            RbacConstant::$role_operation_manager,
            RbacConstant::$role_operation_interns,
            RbacConstant::$role_project_charger,
        ],
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '刪除放量计划',
        'auth_url'  => 'cj-project-volume/delete',
        'parent_url'=>  'cj-project-volume',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  [
            RbacConstant::$role_db_manager,
            RbacConstant::$role_bd_specialist,
            RbacConstant::$role_business_charger,
            RbacConstant::$role_channel_charger,
            RbacConstant::$role_channel_manager,
            RbacConstant::$role_data_operation_specialist,
            RbacConstant::$role_estate_expand,
            RbacConstant::$role_field_manager,
            RbacConstant::$role_operation_manager,
            RbacConstant::$role_operation_interns,
            RbacConstant::$role_project_charger,
        ],
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '放量计划列表',
        'auth_url'  => 'cj-project-volume/view',
        'parent_url'=>  'cj-project-volume',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '放量计划历史数据展示',
        'auth_url'  => 'cj-project-volume/history',
        'parent_url'=>  'cj-project-volume',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '在售房源余量',
        'auth_url'  => 'project-house-onsale',
        'parent_url'=>  'yw-project-list',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '在售房源余量更新',
        'auth_url'  => 'project-house-onsale/update',
        'parent_url'=>  'project-house-onsale',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  [
            RbacConstant::$role_admin,
            RbacConstant::$role_business_charger,
            RbacConstant::$role_bd_specialist,
            RbacConstant::$role_field_manager,
            RbacConstant::$role_project_charger,
            RbacConstant::$role_channel_charger,
            RbacConstant::$role_channel_manager,
            RbacConstant::$role_db_manager,
            RbacConstant::$role_estate_expand,
            RbacConstant::$role_group_expand_charger,
            RbacConstant::$role_group_expand_person,
            RbacConstant::$role_operation_manager,
            RbacConstant::$role_data_operation_specialist,
            RbacConstant::$role_operation_interns,
            RbacConstant::$role_data_specialist,
        ],
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '异步获取房源信息',
        'auth_url'  => 'project-house-onsale/get-house-on-sale-ajax',
        'parent_url'=>  'project-house-onsale',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '在售房源余量历史数据展示',
        'auth_url'  => 'project-house-onsale/history',
        'parent_url'=>  'project-house-onsale',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '楼盘案场数据',
        'auth_url'  => 'cj-case-field',
        'parent_url'=>  'yw-project-list',
        'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '案场数据更新录入',
        'auth_url'  => 'cj-case-field/update',
        'parent_url'=>  'cj-case-field',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  [
            RbacConstant::$role_admin,
            RbacConstant::$role_business_charger,
            RbacConstant::$role_bd_specialist,
            RbacConstant::$role_field_manager,
            RbacConstant::$role_project_charger,
            RbacConstant::$role_channel_charger,
            RbacConstant::$role_channel_manager,
            RbacConstant::$role_db_manager,
            RbacConstant::$role_estate_expand,
            RbacConstant::$role_group_expand_charger,
            RbacConstant::$role_group_expand_person,
            RbacConstant::$role_operation_manager,
            RbacConstant::$role_data_operation_specialist,
            RbacConstant::$role_operation_interns,
            RbacConstant::$role_data_specialist,
        ],
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '案场更新异步获取统计数据',
        'auth_url'  => 'cj-case-field/get-statistics',
        'parent_url'=>  'cj-case-field',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '案场历史数据展示页',
        'auth_url'  => 'cj-case-field/history',
        'parent_url'=>  'cj-case-field',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '服务报告',
        'auth_url'  => 'cj-case-field-service-report',
        'parent_url'=>  'expand',
        'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '服务报告录入',
        'auth_url'  => 'cj-case-field-service-report/create',
        'parent_url'=>  'cj-case-field-service-report',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  [
            RbacConstant::$role_admin,
            RbacConstant::$role_channel_manager,
            RbacConstant::$role_channel_charger,
            RbacConstant::$role_project_charger,
            RbacConstant::$role_field_manager,
            RbacConstant::$role_db_manager,
            RbacConstant::$role_estate_expand,
        ],
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '案场服务报告审核',
        'auth_url'  => 'cj-case-field-service-report/audit',
        'parent_url'=>  'cj-case-field-service-report',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '开发商满意度评价',
        'auth_url'  => 'cj-developer-evaluate',
        'parent_url'=>  'expand',
        'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '开发商满意度评价录入',
        'auth_url'  => 'cj-developer-evaluate/create',
        'parent_url'=>  'cj-developer-evaluate',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  [
            RbacConstant::$role_admin,
            RbacConstant::$role_channel_manager,
            RbacConstant::$role_channel_charger,
            RbacConstant::$role_project_charger,
            RbacConstant::$role_field_manager,
            RbacConstant::$role_db_manager,
            RbacConstant::$role_estate_expand,
        ],
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '开发商满意度评价审核',
        'auth_url'  => 'cj-developer-evaluate/audit',
        'parent_url'=>  'cj-developer-evaluate',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '独家房源',
        'auth_url'  => 'cj-exclusive-house',
        'parent_url'=>  'expand',
        'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '独家房源录入',
        'auth_url'  => 'cj-exclusive-house/create',
        'parent_url'=>  'cj-exclusive-house',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  [
            RbacConstant::$role_admin,
            RbacConstant::$role_channel_manager,
            RbacConstant::$role_channel_charger,
            RbacConstant::$role_project_charger,
            RbacConstant::$role_field_manager,
            RbacConstant::$role_db_manager,
            RbacConstant::$role_estate_expand,
        ],
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '独家房源审核',
        'auth_url'  => 'cj-exclusive-house/audit',
        'parent_url'=>  'cj-exclusive-house',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '驻场楼盘考试成绩',
        'auth_url'  => 'cj-project-exam',
        'parent_url'=>  'expand',
        'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '楼盘考试成绩上传',
        'auth_url'  => 'cj-project-exam/create',
        'parent_url'=>  'cj-project-exam',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '楼盘考试成绩审核',
        'auth_url'  => 'cj-project-exam/audit',
        'parent_url'=>  'cj-project-exam',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  CommonConstant::ADD_ROLE_ALL,
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '驻场楼盘考试成绩列表页',
        'auth_url'  => 'cj-project-exam/index',
        'parent_url'=>  'cj-project-exam',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'       => [
            RbacConstant::$role_admin,              // 总管理员
            RbacConstant::$role_channel_manager,    // 渠道经理
            RbacConstant::$role_channel_charger,    // 渠道主管
            RbacConstant::$role_project_charger,    // 项目主管
            RbacConstant::$role_field_manager,      // 项目专员
        ],
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '户型创建',
        'auth_url'  => 'yw-projects/house-type-create',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'       => RbacConstant::getChannelRole(),     //渠道十个角色
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '户型修改',
        'auth_url'  => 'yw-projects/house-type-update',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'       => RbacConstant::getChannelRole(),     //渠道十个角色
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '户型查看',
        'auth_url'  => 'yw-projects/house-type-view',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'       => RbacConstant::getChannelRole(),     //渠道十个角色
        'creator'   =>  '李阳',
    ],
    [
        'auth_name' => '楼盘管理-新增变更通知',
        'auth_url'  => 'project-change-notify/create',
        'role_type' => CommonConstant::ROLE_TYPE_ADD,
        'role'      =>  [
            RbacConstant::$role_admin,
            RbacConstant::$role_business_charger,
            RbacConstant::$role_bd_specialist,
            RbacConstant::$role_field_manager,
            RbacConstant::$role_project_charger,
            RbacConstant::$role_channel_charger,
            RbacConstant::$role_channel_manager,
            RbacConstant::$role_db_manager,
            RbacConstant::$role_estate_expand,
            RbacConstant::$role_group_expand_charger,
            RbacConstant::$role_group_expand_person,
            RbacConstant::$role_operation_manager,
            RbacConstant::$role_data_operation_specialist,
            RbacConstant::$role_operation_interns,
            RbacConstant::$role_data_specialist,
        ],
        'creator'   =>  '李阳',
    ],

];
