<?php
namespace console\template\auth\common;
/**
 * @author: pengqiucheng<pengqiucheng@julive.com>
 * @date: 2018/8/29
 * [
'auth_url'=>'',	//权限名称
'auth_name'=>'',		//权限路由
'parent_url'=>'',	//父级权限路由
'role_type'=>'',    //角色类型 add新增角色 reduce减少角色 recover覆盖
'role'=>[],			//角色数组 all表示所有角色
'creator'=>'',		//创建人姓名
]
 */


use common\constants\CommonConstant;
use common\constants\RbacConstant;

return [

	//这些条是select2  但是url 没有按照 结尾是-list的来创建    下面请搜索 "按照以下sql"   如果线上多了几条就添加进去
	[
		'auth_name' => '楼盘关键词过滤',
		'auth_url' => 'yw-keywords/check-keywords',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name' => '上传楼盘点评的图片	',
		'auth_url' => 'yw-project-review/up-load-project-comment-img',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name' => '查找未点评的楼盘',
		'auth_url' => 'yw-project-review/find-not-review',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],




//按照以下sql 搜索出 有关上传的 33条 记录  其中下面3条不是上传连接,而是页面    18/10/17
//select name,description from yw_auth_item where type=2 and description like '%上传%'

//'tr-employee/upload-re-exam-score', '楼盘学习-上传补考学习成绩'
//'tr-resource/create', '附件上传权限'
//'yw-payment-info/again-upload-voucher', '回款跟进-重新上传凭证'
	[
		'auth_name'=>'cms图片上传',
		'auth_url'=>'cms-cj-district-analysis/upload-ico',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'feed流落地页管理--组件--上传图片',
		'auth_url'=>'cms-cj-feed-component/upload-img',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'信息流管理-图片批量上传',
		'auth_url'=>'cms-cj-information-flow/img-upload',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'网站页面板块管理上传图片',
		'auth_url'=>'cms-cj-plate-manage/upload-ico',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'案例分析管理上传图片',
		'auth_url'=>'cms-cj-project-case/upload-img',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'APP启动页面-上传banner',
		'auth_url'=>'cms-cj-start-up/upload-banner',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'上传banner图',
		'auth_url'=>'cms-common-banner/upload-banner',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'上传图片--通用',
		'auth_url'=>'cms-common-image/upload-img',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'新建资讯版块_上传图片',
		'auth_url'=>'cms-yw-data-collection-module/upload-img',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'咨询上传文章',
		'auth_url'=>'cms-yw-data-collection/up-data-collection',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'咨询上传图片',
		'auth_url'=>'cms-yw-data-collection/up-data-collection-img',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],

	[
		'auth_name'=>'楼盘变更通知上传图片',
		'auth_url'=>'project-change-notify/img-upload',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'楼盘近况多图片上传',
		'auth_url'=>'project/img-upload',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'文件上传-获取上传签名',
		'auth_url'=>'upload/get-upload-sign',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'图片上传',
		'auth_url'=>'upload/upload-img',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],

	[
		'auth_name'=>'楼盘商务信息管理-上传图片',
		'auth_url'=>'yw-project-business/img-upload',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'添加图片-上传图片',
		'auth_url'=>'yw-project-img-new/img-upload',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'上传楼盘点评的图片',
		'auth_url'=>'yw-project-review/up-load-project-comment-img',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'楼盘信息-上传楼栋图片',
		'auth_url'=>'yw-projects/upload-img',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'咨询师质检更新上传',
		'auth_url'=>'yw-quality-testing-header/save-quality',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'客服质检更新上传',
		'auth_url'=>'yw-quality-testing-server/save-quality',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'签约多图片上传',
		'auth_url'=>'yw-sign/img-upload',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'签约评论图片上传',
		'auth_url'=>'yw-sign/upload',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'上传签约凭证图片',
		'auth_url'=>'yw-sign/upload-sign',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'排号单-认购单照片上传',
		'auth_url'=>'yw-subscribe/upload-subscribe-img',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'动态图片上传',
		'auth_url'=>'yw-user-project-comment/img-upload',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],
	[
		'auth_name'=>'动态图片删除	',
		'auth_url'=>'yw-user-project-comment/delete-img',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      =>  CommonConstant::ADD_ROLE_ALL,
		'creator'   =>  '白少杰',
	],


	[//隐藏权限
	 'auth_name' => '添加图片-删除图片',
	 'auth_url' => 'yw-project-img-new/delete-img',
	 'role_type' => CommonConstant::ROLE_TYPE_ADD,
	 'role' => [
		 RbacConstant::$role_operation_manager,
		 RbacConstant::$role_operation_interns,

	 ],
	 'creator'   =>  '白少杰',
	],


//按照以下sql 搜索出 有关select2 的 111条 记录 18/10/17
//select name,description from yw_auth_item where type=2 and name like '%-list'

	[
		'auth_name'  => '产品需求管理-获取用户需求下拉列表',
		'auth_url' => 'bbs-demand/get-advice-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '侃侃尔坛获取员工下拉',
		'auth_url' => 'bbs-employee/get-employee-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '产品版本列表-需求下拉',
		'auth_url' => 'bbs-employee/get-need-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '产品版本管理-员工下拉',
		'auth_url' => 'bbs-product-version/get-employee-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '楼盘点评审核列表-获取楼盘下拉列表',
		'auth_url' => 'bd-project-comment/get-project-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '业态列表',
		'auth_url' => 'bd-project-dongtai/project-type-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取楼盘组下拉列表',
		'auth_url' => 'bd-project-group/get-bd-group-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取抓取楼盘下拉列表',
		'auth_url' => 'bd-project-group/get-bd-project-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '抓取图片审核列表',
		'auth_url' => 'bd-project-img/audit-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => 'BD列表页-获取合作跟进BD',
		'auth_url' => 'business-order/get-bd-employee-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取某个城市的楼盘列表下拉框',
		'auth_url' => 'business-order/get-project-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '数据维护异步请求获取楼盘户型名称列表',
		'auth_url' => 'cj-house-type-audit/get-house-type-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取字段常量配置下拉列表',
		'auth_url' => 'cj-object-field-config/get-show-group-name-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '楼盘数据维护获取楼盘名称列表',
		'auth_url' => 'cj-project-audit/get-project-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '楼盘动态信息-户型下拉',
		'auth_url' => 'cj-project-dynamic-info/get-house-type-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '渠道管理-获取推广账号',
		'auth_url' => 'cms-channel/get-channel-account-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '渠道管理-获取推广渠道',
		'auth_url' => 'cms-channel/get-channel-type-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '智能分析平台-获取城市下拉',
		'auth_url' => 'cms-cj-district/get-city-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '锚点组件-下拉',
		'auth_url' => 'cms-cj-feed-component/get-point-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '楼盘问问组件-下拉',
		'auth_url' => 'cms-cj-feed-component/get-question-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '落地页管理-活动下拉',
		'auth_url' => 'cms-cj-feed-page/get-activity-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '页面广告位获取对象数据下拉',
		'auth_url' => 'cms-cj-plate-manage/get-object-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '案例分析管理获取关联咨询师',
		'auth_url' => 'cms-cj-project-case/get-employee-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '案例分析管理获取关联楼盘',
		'auth_url' => 'cms-cj-project-case/get-project-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
//	[
//		'auth_name'  => '报警管理-添加报警-报警提醒人',
//		'auth_url' => 'cms-employee/get-employee-dropdown-list',
//		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
//		'role'      => CommonConstant::ADD_ROLE_ALL,
//		'creator'   => '白少杰',
//	],
//	[
//		'auth_name'  => '智能分析平台-获取关键词下拉',
//		'auth_url' => 'cms-idsp-channel-stat/get-keywords-dropdown-list',
//		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
//		'role'      => CommonConstant::ADD_ROLE_ALL,
//		'creator'   => '白少杰',
//	],
//	[
//		'auth_name'  => '智能分析平台-获取计划下拉',
//		'auth_url' => 'cms-idsp-channel-stat/get-plan-dropdown-list',
//		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
//		'role'      => CommonConstant::ADD_ROLE_ALL,
//		'creator'   => '白少杰',
//	],
//	[
//		'auth_name'  => '智能分析平台-获取单元下拉',
//		'auth_url' => 'cms-idsp-channel-stat/get-unit-dropdown-list',
//		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
//		'role'      => CommonConstant::ADD_ROLE_ALL,
//		'creator'   => '白少杰',
//	],
	[
		'auth_name'  => '方案关键词管理-获取关键词下拉',
		'auth_url' => 'cms-idsp-scheme-keywords/get-scheme-keywords-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '方案计划管理-获取方案下拉',
		'auth_url' => 'cms-idsp-scheme-plan/get-scheme-plan-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '方案单元管理-获取单元下拉',
		'auth_url' => 'cms-idsp-scheme-unit/get-scheme-unit-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取区域下拉列表',
		'auth_url' => 'cms-idsp-scheme/get-district-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '方案管理-获取方案下拉',
		'auth_url' => 'cms-idsp-scheme/get-idsp-scheme-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '资讯分类列表',
		'auth_url' => 'cms-yw-data-collection-module/module-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '地图管理-获取标签下拉列表',
		'auth_url' => 'cms-yw-map-tag-content/get-tag-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '客源管理-暂停跟进订单',
		'auth_url' => 'customer-pool/order-pause-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '财务-获取增加审批人select2接口',
		'auth_url' => 'cw-approval/get-employee-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '客户数据分析',
		'auth_url' => 'data-analysis/customer-analysis-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取所有城市json数据',
		'auth_url' => 'district/get-city-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '神秘访客-获取可接单咨询师',
		'auth_url' => 'employee/get-active-employee-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '所有员工下拉框-在职和离职',
		'auth_url' => 'employee/get-all-employee-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '成交单录入-打车人手机号',
		'auth_url' => 'employee/get-didi-mobile-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '员工信息的下拉联想',
		'auth_url' => 'employee/get-employee-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => 'bd单跟进-获取bd单跟进人select2 url',
		'auth_url' => 'employee/get-ex-follower-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '条款审批固定的人下拉框',
		'auth_url' => 'ex-approval-config/get-employee-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取地块下拉框',
		'auth_url' => 'ex-lots/ex-lots-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取开发商人员下拉框',
		'auth_url' => 'ex-partner-employee/ex-partner-employee-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '咨询师审核',
		'auth_url' => 'header/audit-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],

	[
		'auth_name'  => '活动获取关联渠道select2',
		'auth_url' => 'market-activity-info/get-channel-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '营销活动获取员工信息',
		'auth_url' => 'market-activity-info/get-employee-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '活动计划获取员工select',
		'auth_url' => 'market-activity-plan/get-employee-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '活动主推楼盘select2',
		'auth_url' => 'market-activity-project/get-project-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取区域下拉列表',
		'auth_url' => 'project/get-district-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取环线',
		'auth_url' => 'project/get-line-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取楼盘下拉列表数据',
		'auth_url' => 'project/get-project-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],

	[
		'auth_name'  => '报表',
		'auth_url' => 'stat-backend/get-json-stat-table-only-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '任务列表-ajax获取下载资料列表',
		'auth_url' => 'tr-task/ajax-get-resource-down-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '发布任务-获取部门员工',
		'auth_url' => 'tr-task/get-employee-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '发布任务-获取楼盘关联试卷',
		'auth_url' => 'tr-task/get-paper-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '发布任务-获取楼盘下拉',
		'auth_url' => 'tr-task/get-project-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '发布任务-搜索学习资料',
		'auth_url' => 'tr-task/get-resource-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取渠道下拉列表',
		'auth_url' => 'user/get-channel-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取留电口下拉列表',
		'auth_url' => 'user/get-optype-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取友介老客户下拉列表',
		'auth_url' => 'user/get-order-user-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '用户下拉信息',
		'auth_url' => 'user/get-user-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '消息发送列表',
		'auth_url' => 'wxcms-message-template/message-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => 'bd单签约-楼盘下拉列表',
		'auth_url' => 'yw-bd-sign/get-project-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => 'bd单签约_合作方下拉联想',
		'auth_url' => 'yw-bd-sign/get-project-partner-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取咨询师组下拉数据',
		'auth_url' => 'yw-department-architecture/get-team-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '咨询师主管联想下拉-下拉列表',
		'auth_url' => 'yw-department-architecture/get-team-leader-name-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取滴滴订单下拉列表',
		'auth_url' => 'yw-didi-order/get-didi-order-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '商务专员城市配置-下拉列表',
		'auth_url' => 'yw-employee-city/city-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '主推楼盘-楼盘下拉',
		'auth_url' => 'yw-main-push-project/get-project-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '曼哈顿分配策略-列表区域下拉',
		'auth_url' => 'yw-manhattan/get-district-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '曼哈顿分配策略-列表咨询师下拉',
		'auth_url' => 'yw-manhattan/get-employee-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '曼哈顿分配策略-列表楼盘下拉',
		'auth_url' => 'yw-manhattan/get-project-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '新联系列表',
		'auth_url' => 'yw-order-contact/contact-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '标签联动搜索',
		'auth_url' => 'yw-order-tags/get-employee-tags-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '客户备忘-获取当前关系',
		'auth_url' => 'yw-order-tags/get-order-tags-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '批量转移客户',
		'auth_url' => 'yw-order/batch-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '取重复订单数据',
		'auth_url' => 'yw-order/repeat-order-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '楼盘商务信息-获取报备方式下拉',
		'auth_url' => 'yw-project-business/get-report-type-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '楼盘管理',
		'auth_url' => 'yw-project-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '下拉联想获取所有新楼盘',
		'auth_url' => 'yw-project-mainten/get-new-mainten-project-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取公司下拉列表',
		'auth_url' => 'yw-project-partner/get-project-partner-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '楼盘备案合作方下拉列表',
		'auth_url' => 'yw-project-record/get-record-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取品牌开发商下拉',
		'auth_url' => 'yw-projects/get-brand-developer-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '业态下拉数据',
		'auth_url' => 'yw-projects/get-project-type-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '获取区域板块下拉数据',
		'auth_url' => 'yw-projects/get-trade-area-dropdown-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '带看评价管理',
		'auth_url' => 'yw-see-project-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '删除某一次带看的楼盘列表',
		'auth_url' => 'yw-see-project/del-see-project-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '模糊查询楼盘',
		'auth_url' => 'yw-see-project/get-project-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '合作方下拉列表',
		'auth_url' => 'yw-see-project/get-project-partner-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '查看报备列表',
		'auth_url' => 'yw-see-project/get-report-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '新带看列表',
		'auth_url' => 'yw-see-project/see-project-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '特殊线索分配-设备来源',
		'auth_url' => 'yw-select-constant/get-device-list',
		'parent_url'=>  'yw-special-rule',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '特殊线索管理-联系途径下拉',
		'auth_url' => 'yw-select-constant/get-source-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '签约列表页',
		'auth_url' => 'yw-sign-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '认购列表页',
		'auth_url' => 'yw-subscribe-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '城市人力首页',
		'auth_url' => 'zp-city-hr/show-city-hr-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],
	[
		'auth_name'  => '待入职列表',
		'auth_url' => 'zp-group/offer-list',
		'role_type' => CommonConstant::ROLE_TYPE_RECOVER,
		'role'      => CommonConstant::ADD_ROLE_ALL,
		'creator'   => '白少杰',
	],






];
