# Generated by Django 2.0.7 on 2019-02-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail_list_extend',
            field=models.TextField(blank=True, null=True),
        ),
    ]
